OpmImputationBundle:
    resource: "@OpmImputationBundle/Resources/config/routing.yml"
    prefix:   /

OpmUtilisateurBundle:
    resource: "@OpmUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

OpmTestBundle:
    resource: "@OpmTestBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
