parameters:
#    opm_imputation.example.class: Opm\ImputationBundle\Example

services:
#    opm_imputation.example:
#        class: %opm_imputation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
