parameters:
#    opm_utilisateur.example.class: Opm\UtilisateurBundle\Example

services:
#    opm_utilisateur.example:
#        class: %opm_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
