## YAML Template.
---
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    encoders:
        'FOS\UserBundle\Model\UserInterface': sha512

    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /user
                failure_path:   /login
                default_target_path: /user
            logout:
                path:   /logout
                target: /login
            anonymous:    true
            
    role_hierarchy:
      
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN
        ROLE_DEV:      ROLE_DEV

    access_control:
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/images/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/ajax.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/admin/, role: ROLE_ADMIN }
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/user.*, role: ROLE_USER }
        # PAGES ACCESSIBLES AUX DEVELOPPEURS
        - { path: ^/console/, role: ROLE_DEV }