<?php

namespace Opm\ImputationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * baRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class baRepository extends EntityRepository
{
}