<?php

namespace Opm\ImputationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * buRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class buRepository extends EntityRepository
{
}